name: Deploy Storybook

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci 

      - name: Build Storybook
        run: npm run build-storybook -- --output-dir static/storybook-static/ && npm run build
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Build Aplication
        run: npm run build
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      - name: Add .nojekyll to build output
        run: touch static/.nojekyll

      - name: Deploy Branch
        run: npm run deploy-storybook -- --ci --existing-output-dir=static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}